#theme: minima
#theme: ./theme/dist
theme: ./theme

siteConfig:
  title: Chemistry Club
  url: https://chem.istry.club
  author: bad_dubs
  email: author@your-domain.com
  description: Chemistry Club is a long-running monthly Thursday night party in a bar in Neukölln with a diverse crowd and a freesyle music policy.

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about
  social:
    twitter: saber_land
    github: egoist
    rss: true
  disqus: chemistry-club

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true

permalinks:
  post: /:year/:month/:day/:slug
  page: /:slug

